tastie/blog/urls.py
from django.urls import path
from .views import *
from blog import views

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('user/favourites/<str:username>', PostFavouriteListView.as_view(), name='favourites'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('search/', SearchResultsView.as_view(), name='search-results'),
    path('post/<int:pk>/<str:opition>', UpdatePostVote.as_view(), name='requirement_post_vote'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
]

tastie/tastie/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('user_update/', user_views.update_profile, name='update-profile'),
    path('profile/', user_views.profile, name='profile'),
    path('', include('blog.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tastie/blog/models.py
from django.db import models
from django.utils import timezone #to implement location timezone
from django.contrib.auth.models import User #User table inside django project
from django.urls import reverse
from django import forms
from taggit.managers import TaggableManager
from PIL import Image
from django.conf import settings


DIF_CHOICES =(
    ("1", "Easy"),
    ("2", "Intermediate"),
    ("3", "Advanced")
)

class Post(models.Model):

    title = models.CharField(max_length=100)
    content = models.CharField(max_length=200, default='Small Description')
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE) #If user is deleted, all his posts should be deleted too
    image = models.ImageField(default='defaultPost.jpg', upload_to='post_pics')
    difficulty = models.CharField(max_length=40, choices = DIF_CHOICES, default = DIF_CHOICES[1])
    duration = models.CharField(max_length=5, default= '00:30')
    method = models.TextField(default='Method')
    servings = models.CharField(max_length=2, default= '4')
    ingredients = models.TextField(default='Ingredients')
    tags = TaggableManager(blank=True)

    def __str__(self):
        return self.title

    def get_total_likes(self):
        return self.likes.users.count()

    def get_total_dis_likes(self):
        return self.dis_likes.users.count()

    def get_likes(self):
        return self.likes

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk}) #return full path as string

    def save(self,*args, **kwargs): #change save method to resize image passed by the user
        super(Post, self).save(*args, **kwargs)

        img= Image.open(self.image.path) #open image of current instance

        if img.height > 1000 or img.width > 1000:
            output_size = (1000, 1000)
            img.thumbnail(output_size)
            img.save(self.image.path) #save resized image

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

class Like(models.Model):
    ''' like  comment '''

    post = models.OneToOneField(Post, related_name="likes", on_delete=models.CASCADE)
    users = models.ManyToManyField(User, related_name='requirement_post_likes')
    date_liked = models.DateTimeField(default=timezone.now)


class DisLike(models.Model):
    ''' Dislike  comment '''

    post = models.OneToOneField(Post, related_name="dis_likes", on_delete=models.CASCADE)
    users = models.ManyToManyField(User, related_name='requirement_post_dis_likes')

class Comment(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

tastie/blog/forms.py
from .models import Post, Comment
from django import forms

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

tastie/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect, reverse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin #import nedded to require to the user be logged in and be the author to update or delete it
from django.views.generic import RedirectView,TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView, View #class based view
from blog.models import Post, DisLike, Like
from django.contrib.auth.models import User
from django.db.models import Q
from django.urls import reverse
from .forms import CommentForm
from .models import Post, Comment
from django.contrib.auth.decorators import login_required

def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'blog/home.html', context)

class PostListView(ListView):
    model = Post
    paginate_by = 5
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    ordering = ['likes'] #show new posts up in page

class PostFavouriteListView(ListView):
    model = Post
    paginate_by = 5
    template_name = 'blog/favourite.html'
    context_object_name = 'posts'

    def get_queryset(self):
        user = get_object_or_404(User, username =self.kwargs.get('username')) #prevent access to unable profiles
        return Post.objects.order_by('title') #order posts by most recents

class UserPostListView(ListView):
    model = Post
    paginate_by = 8
    template_name = 'blog/user_posts.html'
    context_object_name = 'posts'

    def get_queryset(self):
        user = get_object_or_404(User, username =self.kwargs.get('username')) #prevent access to unable profiles
        return Post.objects.filter(author=user).order_by('-date_posted') #order posts by most recents

class PostDetailView(DetailView):
    model = Post

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'difficulty', 'duration', 'servings', 'image', 'ingredients', 'method', 'tags']

    def form_valid(self, form): #overwrite form validation method
        form.instance.author = self.request.user #set author as logged in user
        post = form.save(commit=False)
        post.save()
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content', 'difficulty', 'duration', 'servings', 'image', 'ingredients', 'method', 'tags']

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author: #verify if the user is the same that posted the recipe
            return True
        return False

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url='/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author: #verify if the user is the same that posted the recipe
            return True
        return False

class SearchResultsView(ListView):
    model = Post
    paginate_by = 8
    template_name = 'blog/search_results.html'
    context_object_name = 'posts'

    def get_queryset(self): # new
        query = self.request.GET.get('q')
        object_list = Post.objects.filter(
            Q(title__icontains=query) | Q(content__icontains=query) | Q(tags__slug__icontains=query) | Q(author__username__icontains=query)
        )
        return object_list.order_by('-date_posted')

class UpdatePostVote(LoginRequiredMixin, View):
    login_url = '/login/'
    redirect_field_name = 'next'

    def get(self, request, *args, **kwargs):

        pk = self.kwargs.get('pk', None)
        opition = self.kwargs.get('opition', None) # like or dislike button clicked

        post = get_object_or_404(Post, id=pk)

        try:
            # If child DisLike model doesnot exit then create
            post.dis_likes
        except Post.dis_likes.RelatedObjectDoesNotExist as identifier:
            DisLike.objects.create(post = post)

        try:
            # If child Like model doesnot exit then create
            post.likes
        except Post.likes.RelatedObjectDoesNotExist as identifier:
            Like.objects.create(post = post)

        if opition.lower() == 'like':

            if request.user in post.likes.users.all():
                post.likes.users.remove(request.user)
            else:
                post.likes.users.add(request.user)
                post.dis_likes.users.remove(request.user)

        elif opition.lower() == 'dis_like':

            if request.user in post.dis_likes.users.all():
                post.dis_likes.users.remove(request.user)
            else:
                post.dis_likes.users.add(request.user)
                post.likes.users.remove(request.user)
        else:
            return redirect('post-detail', pk=pk)
        return redirect('post-detail', pk=pk)

def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            form.instance.author = request.user
            comment.post = post
            comment.save()
            return redirect('post-detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('post-detail', pk=comment.post.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('post-detail', pk=comment.post.pk)

tastie/blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}
    <h1>Tastie! About.</h1>
{% endblock content %}

tastie/blog/templates/blog/add_comment_to_post.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New comment</h1><br>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-success">Send</button>
    </form>
{% endblock %}

tastie/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% if title %}
      <title>Tastie! - {{ title }} </title>
    {% else %}
      <title>Tastie!</title>
    {% endif %}
    {{ form.media }}
    <link href='https://fonts.googleapis.com/css?family=Anton' rel='stylesheet'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <link rel="stylesheet" href="{% static 'blog/main.css' %}">
  <body>

    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="logo text-warning navbar-brand mr-4" href="/"> TASTIE! </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="{% url 'blog-home' %}">Feed</a>
              <a class="nav-item nav-link" href="{% url 'post-create' %}">Post!</a>
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'user-posts' user.username %}">My Recipes</a>
                <a class="nav-item nav-link" href="{% url 'favourites' user.username %}">Favourites</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">My Recipes</a>
                <a class="nav-item nav-link" href="{% url 'login' %}">Favourites</a>

              {% endif %}

            </div>

            <!-- Navbar Right Side -->
            <div class="navbar-nav ml-auto">
              <form class="search-form mr-5" action="{% url 'search-results' %}" method="get">
                <input type="text" name="q" id="id_q" class="form-control" placeholder="Search">
              </form>
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
              {% endif %}
              </div>
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container ">
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 mt-2">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>

        <div class="col-md-2"></div>
      </div>
    </main>

    <script>
      document.getElementById('id_q').value = '{{ query }}'
    </script>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

tastie/blog/templates/blog/favourite.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
  <div class="infinite-container">
    {% for post in posts %}
    {% if request.user in post.likes.users.all%}
      <div class="infinite-item">
        <div class="card mb-4">
          <div class="media m-0 mt-3">
        	  <div class="d-flex mr-3">
        			<a href="{% url 'user-posts' post.author.username %}"><img class="rounded-circle article-img ml-4 mr-1"src="{{ post.author.profile.image.url }}" alt="Profile Pic"></a>
        		</div>
        		<div class="media-body">
        		  <p class="m-0 mt-2 anton-font"><a href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a></p>
        		  <span class="text-muted small-text">Posted: {{ post.date_posted|date:"d/m/Y G:i" }}</span>
        	  </div>
          </div>
          <hr>
          <div class="card-body">
            <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="lead text-muted text-justify small-text mt-2 mb-3">Description: {{post.content}}</p>
            <a href="{% url 'post-detail' post.id %}"><img class="card-img-top rounded mt-2 mb-3" src="{{ post.image.url }}" alt="Card image cap"></a>
            <a href="{% url 'post-detail' pk=post.pk %}">Comments: {{ post.comments.count }}</a>
          </div>
        </div>
      </div>
      {% endif %}
    {% endfor %}
  </div>





  {% if page_obj.has_next %}
    <a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}"></a>
  {% endif %}

  <script src="{% static 'blog/js/jquery-3.1.1.min.js' %}"></script>
  <script src="{% static 'blog/js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'blog/js/infinite.min.js' %}"></script>

  <script>
    var infinite = new Waypoint.Infinite({
      element: $('.infinite-container')[0],
    });
  </script>

{% endblock content %}

tastie/blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
  <div class="infinite-container">
    {% for post in posts %}
      <div class="infinite-item">
        <div class="card mb-4">
          <div class="media m-0 mt-3">
        	  <div class="d-flex mr-3">
        			<a href="{% url 'user-posts' post.author.username %}"><img class="rounded-circle article-img ml-4 mr-1"src="{{ post.author.profile.image.url }}" alt="Profile Pic"></a>
        		</div>
        		<div class="media-body">
        		  <p class="text-info m-0 mt-2 anton-font"><a href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a></p>
        		  <span class="text-muted small-text">Posted: {{ post.date_posted|date:"d/m/Y G:i" }}</span>
        	  </div>
          </div>
          <hr>
          <div class="card-body">
            <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="lead text-muted text-justify small-text mt-2 mb-3">Description: {{post.content}}</p>
            <a href="{% url 'post-detail' post.id %}"><img class="card-img-top rounded mt-2 mb-3" src="{{ post.image.url }}" alt="Card image cap"></a>
            <a href="{% url 'post-detail' pk=post.pk %}">Comments: {{ post.comments.count }}</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>





  {% if page_obj.has_next %}
    <a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}"></a>
  {% endif %}

  <script src="{% static 'blog/js/jquery-3.1.1.min.js' %}"></script>
  <script src="{% static 'blog/js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'blog/js/infinite.min.js' %}"></script>

  <script>
    var infinite = new Waypoint.Infinite({
      element: $('.infinite-container')[0],
    });
  </script>

{% endblock content %}

tastie/blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
      <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">
            Delete Recipe
          </legend>
          <h2>Do you really want to delete the "{{ object.title }}" Recipe?</h2>
        </fieldset>
        <div class="form-group">
          <button class="btn btn-danger" type="submit" name="button">Delete</button>
          <a class="btn btn-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
        </div>
      </form>
    </div>
{% endblock content %}

tastie/blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
  <article class="media content-section">
    <div class="col">

          <!-- Title -->
          <div class="">
            {% if object.author == user %}
              <a role="button" class="test float-right mt-1" type="button" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="caret">
                <a class="icon-bar"></a>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <li><a class="dropdown-item" href="{% url 'post-update' object.id %}"> Update </a></li>
                  <li><a class="dropdown-item " href="{% url 'post-delete' object.id %}"> Delete </a></li>
                </ul>
              </a>
            {% endif %}
            <h1 class="mt-3 mb-3 anton">{{ object.title }}</h1>


          <hr>
          <!-- Author -->
          <p class="lead text-muted small-text mt-2">
            by
            <a href="{% url 'user-posts' object.author.username %}">{{ object.author }}</a>
            <small class="small-text float-right">Posted on {{ object.date_posted|date:"F d, Y" }}</small>
          </p>
          <hr>

          <!-- Preview Image -->
          <img src="{{ post.image.url }}" alt="post-image" class="img-fluid rounded mx-auto d-block  post-image">
          </div>
          <!-- Difficulty servings and duration -->
          <hr>
          <p class="text-muted small-text">Difficulty: {{ object.get_difficulty_display }}  &nbsp|&nbsp  Servings: {{ object.servings }}  &nbsp|&nbsp  Duration: {{ object.duration }}</p>
          <hr>

          <!-- Content Ingredients and method -->
          <p class="lead text-muted small-text mt-2 mb-2">Description: {{object.content}}</p>
          <hr>
          <div class="block">
            <div class="row">
              <div class="span4">
                <span class="text-muted mb-1 ml-3">Ingredients:</span><br>
                <div class="ml-4 mt-1 mb-3">{{ object.ingredients|linenumbers|linebreaks}}</div>
                <div class="mt-4">
                  <span class="text-muted mb-1 ml-3 ">Method:</span><br>
                  <div class="ml-4 mb-5 mt-1 mr-4 text-justify">{{ object.method|linebreaks}}</div>
                </div>

              </div>
            </div>
          </div>

          <footer class="page-footer font-small">

          <div class="footer-copyright float-right py-3 text-muted small-text">Tags:
            {% for tag in object.tags.all %}
              <a href="/search/?q={{ tag.name }}"> #{{ tag.name }}</a>
            {% endfor %}
          </div>

              <div class="text-left">
                 <span class="pointer">
                    {% if request.user in post.likes.users.all%}
                    <!-- already liked-->
                    <a href='{% url "requirement_post_vote" pk=post.pk opition='like' %}'> <i
                       data-toggle="tooltip" data-placement="bottom" title="Unlike"
                       class="like fas fa-thumbs-up pr-1 pt-4" style="color:green; font-size:0.8em;">
                    <span style="font-family: Arial, Helvetica, sans-serif;">{{post.get_total_likes}}</span>
                    </i>
                    </a>
                    {% else %}
                    <!--not liked-->
                    <a href="{% url 'requirement_post_vote' pk=post.pk opition='like' %}"><i
                       data-toggle="tooltip" data-placement="bottom" title="Like"
                       class="default-icon fas fa-thumbs-up pr-1 pt-4" style="color:gray; font-size:0.8em;">
                    <span style="font-family: Arial, Helvetica, sans-serif;">{% if post.get_total_likes  %}{{post.get_total_likes}} {% else %} 0
                    {% endif %}</span></i>
                    </a>
                    {% endif %}
                 </span>
                  <!--dislike-->
                 <span class="ml-3 pointer">
                 {% if request.user in post.dis_likes.users.all %}
                 <a href="{% url 'requirement_post_vote' pk=post.pk opition='dis_like' %}"><i
                    data-toggle="tooltip" data-placement="bottom" title="i dislike this"
                    class="dislike fas fa-thumbs-down pr-1 pt-4" style="color:red; font-size:0.8em;">
                 <span style="font-family: Arial, Helvetica, sans-serif;">{{post.get_total_dis_likes}}</span></i>
                 </a>
                 {% else %}
                 <a href="{% url 'requirement_post_vote' pk=post.pk opition='dis_like' %}"><i
                    data-toggle="tooltip" data-placement="bottom" title="i dislike this "
                    class="default-icon fas fa-thumbs-down pr-1 pt-4" style="color:gray; font-size:0.8em;">
                 <span style="font-family: Arial, Helvetica, sans-serif">{% if  post.get_total_dis_likes %}{{post.get_total_dis_likes}}
                 {% else %} 0 {% endif %}</span></i>
                 </a>
                 {% endif %}
                 {% if user.is_authenticated %}
                   <a class="btn btn-info ml-5" href="{% url 'add_comment_to_post' pk=post.pk %}">Add comment</a><hr>
                  {% else %}
                    <span class="text-muted ml-5"> Log in to leave a comment!</span>
                 {% endif %}
              </div>


              <div class="row bootstrap snippets mt-5">
                      <div class="comment-wrapper">
                          <div class="panel panel-info">
                              <div class="panel-body">
                                  <ul class="media-list">
                                    {% for comment in post.comments.all %}
                                        {% if user.is_authenticated or comment.approved_comment %}
                                        <li class="media">
                                            <a href="{% url 'user-posts' post.author.username %}" class="pull-left">
                                                <img src="{{ comment.author.profile.image.url }}" alt="" class="rounded-circle article-img">
                                            </a>
                                            <div class="media-body">
                                                <span class="text-muted pull-right">
                                                <a href="{% url 'user-posts' post.author.username %}" class="pull-left">
                                                <strong class="text-success">{{ comment.author }}</strong></a>
                                                <small class="text-muted">{{ comment.created_date|date:"d/m/Y G:i" }}</small>
                                                {% if object.author == user or post.author == user or comment.author == user %}
                                                  <a role="button" class="test mt-1 ml-5" type="button" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="caret">
                                                    <a class="icon-bar"></a>
                                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                                      <li><a class="dropdown-item " href="{% url 'comment_remove' comment.id %}"> Delete </a></li>
                                                    </ul>
                                                  </a>
                                                {% endif %}
                                                <p>
                                                    {{ comment.text|linebreaks }}
                                                </p>
                                            </div>
                                        </li>


                                        {% endif %}
                                    {% empty %}
                                        <p>No comments here yet.</p>
                                    {% endfor %}
                                  </ul>
                              </div>
                          </div>
                      </div>
                    </div>

        </footer>
    </div>


  </article>








{% endblock content %}

tastie/blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">
            Recipe Post
          </legend>
          {{ form|crispy }}
        </fieldset>
        <div class="form-group">
          <button class="btn btn-success btn-lg btn-block" type="submit" name="button">Upload!</button>
        </div>
      </form>
    </div>
{% endblock content %}

tastie/blog/templates/blog/search_results.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
  <div class="infinite-container">
    {% for post in posts %}
      <div class="infinite-item">
        <article class="media content-section">
          <img class="rounded-circle article-img"src="{{ post.author.profile.image.url }}" alt="Profile Pic">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"d/m/Y G:i" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
          </div>
        </article>
      </div>
    {% endfor %}
  </div>

  {% if page_obj.has_next %}
    <a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"></a>
  {% endif %}

  <script src="{% static 'blog/js/jquery-3.1.1.min.js' %}"></script>
  <script src="{% static 'blog/js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'blog/js/infinite.min.js' %}"></script>

  <script>
    var infinite = new Waypoint.Infinite({
      element: $('.infinite-container')[0],
    });
  </script>

{% endblock content %}